project:
  type: website

website:
  page-navigation: true
  title: "Sarah Schwartz Stats"
  description: "Transparent and Reproducible Research with R"
  
  navbar: 
    left:  
      - text: "Teaching"
        href: teaching.qmd
      - text: "eBooks"
        href: encyclopedia_vol.qmd
    right: 
      - text: "About"
        href: about.qmd
  
  sidebar:
    background: "#D9E3E4"
    logo: "images/hex_headshot.png"
    style: "docked"
    search: true
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sarbearschwartz
        text: "GitHub organization"
        

    contents:
      - section: "TEACHING"
        contents:
          - href: teaching.qmd
            text: "Overview"
          - href: r4research.qmd
            text: "Using R for Research"
          - href: foundation.qmd
            text: "6600: Stat Foundations"
          - href: regression.qmd
            text: "7610: Regression Analysis"
          - href: mlm.qmd
            text: "7650: Multilevel Modeling"
            
      - section: "ENCYCLOPEDIA"
        contents:
          - href: encyclopedia_vol.qmd
          
      - section: "RESOURCES"
        contents:
          - href: youtube.qmd
            text: YouTube
          - href: skeletons.qmd
            text: Skeletons      


    
  back-to-top-navigation: true
  

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Sarah E Schwartz"
    background: "#D9E3E4"

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    

freeze: auto  

editor: visual

